[build]
publish = "dist/static"
command = "npm run build"
[dev]
command = "npm run dev"

[template.environment]
OPENAI_API_KEY = "your OpenAI API key"
PINECONE_API_KEY = "your Pinecone API key"
PINECONE_ENVIRONMENT = "your Pinecone environment"